name : GIthub Pages Deploy

on:  
  push: 
    branches: 
      - dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: master
          publish_dir: ./build

