name: Test
run-name: ${{github.actor}} just push the ${{github.repository}}
on: [fork]
jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "💡 The ${{ github.actor }} just forked ${{github.repository"
  
    