# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy oto

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
        with:
          branch: master
          clean: true
          clean-exclude: |
            CNAME
